- name: Publish to TestPyPI
  if: github.ref == 'refs/heads/dev'
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    repository-url: https://test.pypi.org/legacy/

- name: Publish to PyPI
  if: github.event_name == 'release'
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    password: ${{ secrets.PYPI_API_TOKEN }}
